### ISSUE TITLE
Check: Both contact sensors with the same entity

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#92]
Check whether it is intended that the lock-out protection takes effect if both contact sensors use the same sensor.

**Comment by cybe** [comment]
Hi!

I just ran into the issue where the ventilation trigger does not open the cover. I have both the ventilation and the lockout protection active while using the same sensor. Is this the issue you're describing here?

When I disable the lockout protection and leave only the ventilation feature active, ventilation works as expected.

Trace: [trace automation.cca_dennis_rolladen_terrasse_links 2024-07-11T17_01_13.695891+00_00.json](https://github.com/user-attachments/files/16181141/trace.automation.cca_dennis_rolladen_terrasse_links.2024-07-11T17_01_13.695891%2B00_00.json)

What would be the expected behavior when using both features? I guess ventilation should move the cover immediately when the sensor is triggered. And lockout protection only prevents closing of the cover when triggered by the usual events like shading, time, sun position or brightness?

**Comment by cybe** [comment]
> I guess ventilation should move the cover immediately when the sensor is triggered. And lockout protection only prevents closing of the cover when triggered by the usual events like shading, time, sun position or brightness?

This seems to be the case. I currently only have ventilation activated. And even if the sensor is `open/on` the cover closes on the brightness trigger. Although I like to leave it open.

Would a workaround be to clone the sensor? So the automation sees two different entities?

**Comment by hvorragend** [comment]
Refs: https://community.home-assistant.io/t/cover-control-automation-cca-a-comprehensive-and-highly-configurable-roller-blind-blueprint/680539/969

**Comment by airmaxx** [comment]
Tanks for giving this high priority. Yes, I understand that it is difficult to take all eventualities into account. Here are my thoughts on these complex dependencies.

The lock-out protection is currently implemented in such a way that it prevents the roller shutters from moving (in any case as far as I understood). That makes sense if the contact sensor is open. If it is closed or changes its status, other rules (ventilation mode) should take precedence. This still prevents you from being locked out. It might even be possible to link to the lock-out protection that the roller shutter is fully opened when the contact sensor opens (regardless of a ventilation mode).

**Comment by airmaxx** [comment]
Today I've experienced the ventilation mode, with automatic daily closing, without lockout protection being enabled.

I can revise my previous post - it works quite well if you set the ventilation mode to a level that also works as a lockout protection.

**Comment by airmaxx** [comment]
I have to spam here ;)
I now understand the problem: without lockout protection, the cover goes into sun protection mode even if the contact/door is open.
My suggestion would be to add an individual configuration option: Prevent sun protection (and closing in the evening) while the contact is open - or add this as a rule to the lockout protection and let the cover move when the contact is closed (even if the lockout protection is enabled).

**Comment by matspi** [comment]
Wouldn’t it make sense to allow opening movements while lockout is true?
The purpose of the anti-lockout feature is - at least to my understanding - to prevent the blinds from closing while you are possibly outside. 

So, when the blinds are closed due to shading being active, and we go to ventilation and lockout mode at the same time, the blinds should be allowed to open. In case the ventilation state would be “more closed” than the current state, the blinds should not move.

**Comment by hvorragend** [comment]
Fixed in version 2024.09.04.
